### PR TITLE
Update Svelte to v3

### PR DESCRIPTION
**Pull request by geoffrich**
This PR updates Svelte to v3 and refactors the components accordingly.

Changes:
- Use Svelte v3 syntax and .svelte file extension
- Use Svelte `tick` function after DOM interactions in tests so component state is updated
- Use `@babel/preset-env` for transpiling Svelte components -- I was getting `Class constructor SvelteComponent cannot be invoked without 'new'` errors with the existing Babel setup

Screenshot of built site:
image

### CODE REVIEW

**Comment by geoffrich** [comment]
@googlebot I signed it!

**Comment by geoffrich** [comment]
Looks like the failing CI is due to #473. Any way to get this fixed?

**Comment by robdodson** [comment]
Let me see if I can get the tests to run locally. I've been neglecting this repo and need to update it to GH Actions

**Comment by robdodson** [comment]
looks good, thank you!

**Pull request merged**
