### PR TITLE
Revise heading structure to improve accessibility

### LINKED ISSUE #801: Accessibility: Repetitive heading structure for screen readers
Hey, thanks for the awesome site! This has been _super_ useful for some web components research I've been doing!

I noticed one issue that could potentially make the site difficult to navigate for screen reader users (or search engine crawlers).

Screen reader users can navigate the page by jumping to headings (`h1`, `h2`, `h3`, etc.) For example, in VoiceOver you can use the "rotor" feature to get a list of all headings on the page and then jump to a specific heading based on it's text. This can be a very quick way to navigate the page.

For example imagine a screen reader user was interested in compatibility between React and web components. They hit the home page, open the rotor, and search for a heading containing the text "React." This is the heading structure they see instead:

```
H1 — Custom Elements Everywhere 
H2 — Making sure frameworks and custom elements can be BFFs 🍻 
H2 — What's this? 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H2 — Frequently Asked Questions 
H3 — What are these custom element things? 
H3 — Are you testing that libraries let you author custom elements? 
H3 — Why is each test counted twice? 
H3 — How are the libraries scored? 
H3 — How are basic and advanced tests different? 
H3 — I thought the whole point of Polymer was to write custom elements. Why doesn't it get a 100%? 
H3 — If a library is missing a feature, like declarative event or property bindings, does it automatically fail those tests? 
H3 — Why don't you have tests for _____ library? 
H3 — I want to write some tests for _____ library. Do you accept pull requests? 
```

This was output by running this snippet on the home page: 

```
[...document.querySelectorAll('h1, h2, h3, h4, h5, h6')].forEach(heading => {
  console.log(`${heading.tagName} — ${heading.innerText}`)
});
```

As you can see, it would be difficult to find information about React using the rotor heading navigation strategy. Instead they'd need to search the page for a string containing "react" or read through the full document.

Similarly search engines use headings to determine and catalogue page content. If the headings do not describe the content well it can be difficult for search engines to understand the content.

I think each framework section should likely have a heading structure like this instead:

```
H3 — React
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
```

Ideally this change would be made without any visual changes by using CSS to maintain the current styles and layout.

Let me know what you think. I could spend some time putting together a PR if this is something you're interested in.

Thanks!

### PR DESCRIPTION
**Pull request by Paul-Hebert**
## Overview

Previously the headings were repetitive and did not list the frameworks.
This could make it difficult to navigate with a screen reader.
It could also make it harder for search engines to understand the content.

To improve this a couple changes were made:
- Framework names were promoted to `h3`s
- "No issues found" is no longer a heading

Luckily all heading styling was applied via classes so no CSS changes were needed.

## Screenshots

_No visual changes_

## Testing

Build the site locally, then run this code snippet to output the heading structure:

```
[...document.querySelectorAll('h1, h2, h3, h4, h5, h6')].forEach(heading => {
  console.log(`${heading.tagName} — ${heading.innerText}`)
});
```

It should output the following:

```
H1 — Custom Elements Everywhere 
H2 — Making sure frameworks and custom elements can be BFFs 🍻 
H2 — What's this? 
H3 — Angular 8.2.14 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — AngularJS (1.x) 1.7.9 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — DIO 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Dojo 6.0.4 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — hybrids 4.1.8 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — hyperHTML 2.32.2 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Lit Element 0.7.1 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Mithril 1.1.7 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Polymer 3.4.1 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Preact 10.0.1 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — React 16.13.1 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Riot.js 4.12.2 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Skate w/ Preact 5.2.4 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Solid 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Stencil 1.8.11 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Surplus 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Svelte 2.16.1 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H3 — Vue 2.6.11 
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
H2 — Frequently Asked Questions 
H3 — What are these custom element things? 
H3 — Are you testing that libraries let you author custom elements? 
H3 — Why is each test counted twice? 
H3 — How are the libraries scored? 
H3 — How are basic and advanced tests different? 
H3 — I thought the whole point of Polymer was to write custom elements. Why doesn't it get a 100%? 
H3 — If a library is missing a feature, like declarative event or property bindings, does it automatically fail those tests? 
H3 — Why don't you have tests for _____ library? 
H3 — I want to write some tests for _____ library. Do you accept pull requests? 
```

---

Let me know if you'd like any changes!

Fixes #801

### CODE REVIEW

**Comment by Paul-Hebert** [comment]
I'm making this contribution on behalf of my employer, [Cloud Four](https://cloudfour.com/) so I'll need to check with them about the CLA before signing.

**Comment by robdodson** [comment]
You can ignore the travis failure, I think I broke the setup a while back and PRs haven't been able to use travis.

But the change looks really small and useful so it looks good to me. Let me know if Cloud Four is ok with you signing the CLA.

**Comment by Paul-Hebert** [comment]
Thanks @robdodson ! I submitted the CLA and a representative of Cloud Four signed the electronic contract. Let me know if there's anything else we need to do on our end. I'm exctied to see this get merged in!

**Comment by robdodson** [comment]
Rad thank you @Paul-Hebert !

**Comment by Paul-Hebert** [comment]
Thank you!

**Pull request merged**
