### PR TITLE
Preact: Add note about properties that start with on

### PR DESCRIPTION
**Pull request by balloob**
In Preact (and any other framework using JSX), it's impossible to set a property that starts with "on". 

https://twitter.com/justinfagnani/status/1103155864322498561

### CODE REVIEW

**Comment by justinfagnani** [comment]
I think this deserves a test, but it'd be nice if all the event name tests rolled up to "declarative event listeners work with any event name" and then that test had a x/10 score.

**Comment by robdodson** [comment]
Should this note be added to other libraries on the site as well such as React? I'm not sure off the top of my head if any of the others use JSX or have similar limitations.

As Justin pointed out, creating a test for this may be a better approach as that would let us accurately measure across libraries.

**Comment by robdodson** [comment]
It looks like angular can't do this either. Here's what my element looks like:

```js
@Component({
  template: `
    <div>
      <ce-with-properties id="wc"
        [bool]="data.bool"
        [num]="data.num"
        [str]="data.str"
        [arr]="data.arr"
        [obj]="data.obj"
        [one]="data.one"
      ></ce-with-properties>
    </div>
  `
})
export class ComponentWithProperties {
  data = {
    bool: true,
    num: 42,
    str: 'Angular',
    arr: ['A', 'n', 'g', 'u', 'l', 'a', 'r'],
    obj: { org: 'angular', repo: 'angular' },
    one: 'two'
  }
}
```

This line `[one]="data.one"` causes a template compile error:

```
Error: Template parse errors:
        Binding to event property 'one' is disallowed for security reasons,please use (e)=...
        If 'one' is a directive input, make sure the directive is imported by the current module. ("
                [arr]="data.arr"
                [obj]="data.obj"
                [ERROR ->][one]="data.one"
              ></ce-with-properties>
            </div>
        "): ng:///DynamicTestModule/ComponentWithProperties.html@8:8
            at syntaxError (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:2700:17)
            at TemplateParser.parse (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:20875:19)
            at JitCompiler._parseTemplate (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:26441:37)
            at JitCompiler._compileTemplate (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:26428:23)
            at eval (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:26371:62)
            at Set.forEach (<anonymous>)
            at JitCompiler._compileComponents (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:26371:19)
            at eval (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:26289:19)
            at Object.then (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:2691:77)
            at JitCompiler._compileModuleAndAllComponents (webpack:///./node_modules/@angular/compiler/fesm5/compiler.js?:26287:26)
```

cc @robwormald just in case I'm doing something silly.

**Review by rictic — CHANGES_REQUESTED** [review]
As pointed out in the comment thread, this is a good change, but it applies to other libraries too. I think it'd be best have this as a test on all libraries rather than a comment only in the preact summary.

**Pull request closed without merging**
