### PR TITLE
Updates Dojo Dependency to v5.0.0

### PR DESCRIPTION
**Pull request by agubler**
Updates the dojo implementation to version 5.0.0.

Also changes all the "Dojo 2" references, to "Dojo".

### CODE REVIEW

**Comment by agubler** [comment]
Hi all! This updates dojo to the latest 4.0.0 release and change the "dojo 2" references to "dojo". Be great to get this in at some point! Thanks!

**Comment by robdodson** [comment]
Hi @agubler sorry for the delay. My current project is in crunch mode so I haven't had a lot of time to dedicate to this repo. I will try to review this PR as soon as things free up a bit.

**Comment by agubler** [comment]
@robdodson No worries, I think we've all been in crunch mode! Thank you!

**Comment by agubler** [comment]
@robdodson Dojo 5.0.0 is out now, if I update the dependencies and stuff again do you think you'll have time to review and merge any time soon?

**Comment by robdodson** [comment]
Hi @agubler sorry for the delay. Yes if you're able to update the dependencies (and the tests don't fall over) then I think we can quickly merge. Sorry for the lag.

**Comment by agubler** [comment]
@robdodson Thanks! I've updated the Dojo implementation to the latest release, 5.0.0. CI seems to be failing, but I'm not sure why... Please let me know if it's something that I need to update.

**Comment by robdodson** [comment]
looking in to the CI issue...

**Comment by robdodson** [comment]
Hm... I'm not sure what's goin on there but it's annoying. Let me see if I can get the tests to pass locally.

**Comment by robdodson** [comment]
Just started reviewing :)

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
I think this looks good to merge.

**Comment by agubler** [comment]
Thanks @robdodson!

**Pull request merged**
