### PR TITLE
Add Hyperapp

### PR DESCRIPTION
**Pull request by zaceno**
Add Hyperapp to the list of frameworks tested.

### CODE REVIEW

**Comment by zaceno** [comment]
@googlebot I signed it!

**Comment by zaceno** [comment]
@googlebot I fixed it!

**Comment by zaceno** [comment]
Sorry, I realized that my diff has a lot of unnecessary whitespace changes. Will fix them shortly.

**Comment by zaceno** [comment]
There I'm happy with the diff now. Welcome to review and merge this! 🙏

**Comment by zaceno** [comment]
> @okwolf  Not sure this would be much of an improvement, but couldn't the same be accomplished with subscriptions?

Yeah maybe probably. Or using the newer version that returns dispatch – that would be even cleaner. Anyway it doesn't matter because in hyperapp you would never add an event-listener imperatively like this. I just did it to prove it was possible so we could score full marks.

Anyhow, I get the feeling this custom-elements project is dead. Hundreds of bot-generated PRs are waiting for review so... not holding my breath 😄

**Review by jorgebucaran — APPROVED** [review]
@robdodson LGTM. Anything else we need to do here to merge here?

**Comment by zaceno** [comment]
Updated to latest hyperapp version (and locked the version in package.json) just because why not :)

**Review by rictic — APPROVED** [review]
Looks great, will merge once tests pass

**Pull request merged**
