### PR TITLE
add svelte tests

### PR DESCRIPTION
**Pull request by UnwrittenFun**
Adds [svelte](https://github.com/sveltejs/svelte) to the list 😄

### CODE REVIEW

**Comment by robdodson** [comment]
This is amazing, thank you @UnwrittenFun! I'm reviewing it all now

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
Thank you again @UnwrittenFun! I just merged in this change, and added a step to compile the components down to ES5 and load in the custom-elements-es5-adapter. I just did that to be consistent with the other tests. So excited to finally have Svelte on the site! 🍻

**Comment by UnwrittenFun** [comment]
Awesome, thanks  🎉

**Pull request merged**
