### PR TITLE
Add Solid implementation

### PR DESCRIPTION
**Pull request by ryansolid**
Solid is a small, fast fine-grained precompiled UI library designed with webcomponents in mind. https://github.com/ryansolid/solid.

Please add it to your test suite.

### CODE REVIEW

**Comment by ryansolid** [comment]
As far as I can tell there isn't anything wrong with the pull request. Am I missing anything?

**Comment by robdodson** [comment]
Hi Ryan, sorry for not following up on this sooner. As the site has grown I've been trying to figure out criteria that libraries should meet before I can add them to the site. The problem is that the more libraries get added, the harder it is to scale and maintain the site, especially when I want to add new tests.

Originally I was thinking of setting a threshold that libraries needed to have a certain number of GitHub stars in order to be added. I realize stars are a sketchy metric, but I need some way to gauge the long term health of a project. Other folks suggested that an alternative would be to provide a way for library authors to maintain the test themselves and phone the results back.

Unfortunately I haven't had time to delve into this much more but I think I may need to hold off on adding any more libraries to the site until I have some better criteria. I should have some time to look into this after Google I/O is behind me.

**Comment by brodybits** [comment]
Thanks @robdodson for the response. I would like to highly recommend that you consider including Solid in the near term, due to the quality it has shown in its design, clean React-like API, and high position in <https://github.com/krausest/js-framework-benchmark> (see <https://krausest.github.io/js-framework-benchmark/current.html>).

While I do have a couple of hopefully constructive critiques, which I will voice on Solid itself, I think Solid should be used to help set the quality bar that should be used for comparing the various Web UI frameworks.

**Comment by robdodson** [comment]
Thanks @brodybits. I'd really like to find a way to include every library that wants their scores to show up on the site. Let me see if I can follow up this weekend with some ideas.

**Comment by ryansolid** [comment]
I really appreciate it. I understand I'm the small guy here, and completely appreciate your position. I will try my best to reach any criteria I can, but I understand if the size of the project today does not merit attention.

I will say from a web component perspective, Solid does try to offer something unique including Semi Synthetic Event Delegation that works over nested Shadow Roots, React-like Portals that use ShadowDOM, and a Custom Element friendly React-like Suspense API. Ok done selling. Thanks.

**Comment by robdodson** [comment]
Well I didn't get very far with this. Unfortunately I'm pretty slammed with work getting ready for Google I/O so I probably won't have much time to do engineering work on a universal solution until at least late May.

Maybe we can use this as a space to discuss what kind of solution would work well for library/framework authors. I think what I'd like to do is have a core set of tests for frameworks with very large communities (React, Angular, Vue, etc) and I'm ok maintaining that small set.

Beyond that, I'd like to create a way for authors to grab the vanilla elements from the repo, author corresponding tests, and phone home the JSON results. I guess we could even do this today by letting authors clone the repo, write their tests, and then have some sort of spot where they can just upload the final JSON.

Maybe we could have the JSON in a repo and a bot auto-merges PRs from library authors? Another alternative would be to have some endpoint where folks can POST their results or a form where they can upload them. I'm not sure what authors would prefer but ideally it should be automated on both their end and ours.

**Comment by robdodson** [comment]
@ryansolid would you mind rebasing the PR to clean up conflicts? I think we should go ahead and land this.

**Comment by ryansolid** [comment]
Awesome. I've rebased I just want to make sure everything still works properly. I will update when I'm ready for the merge.

**Comment by ryansolid** [comment]
Ok it all looks good now. Merge at will.

**Comment by robdodson** [comment]
Thanks Ryan 👍

**Pull request merged**
