### PR TITLE
Rename handleEvent to handleTestEvent. Update Moon

### PR DESCRIPTION
**Pull request by robdodson**
@chasenlehara, @WebReflection, @kbrsh FYI

### CODE REVIEW

**Comment by WebReflection** [comment]
LGTM but it might clash with latest CanJS changes where they've fixed the bind in both adding and removing listeners (and used native/platform `handleEvent` behaviors instead)

**Comment by chasenlehara** [comment]
@WebReflection Thanks for looking out. I’m happy to rebase my PR after this gets merged in.

**Comment by kbrsh** [comment]
@robdodson Looks good as far as the `el` to `root` for Moon. The templates do work with whitespace, it's just that Moon compiles the first element it can find (like React, you cannot have multiple elements at a root returned from a render function).

In this case, when you have a template like:

```js
Moon.component('ComponentWithoutChildren', {
  template: `
    <div>
      <ce-without-children id='wc'></ce-without-children>
    </div>
  `.trim()
  });
```

The first thing Moon compiles is the text element. You can just remove the starting newline and Moon will compile the template correctly:

```js
Moon.component('ComponentWithoutChildren', {
  template: `<div>
      <ce-without-children id='wc'></ce-without-children>
    </div>`
  });
```

Sorry about the constraint, I try to do everything I can to keep it as small as possible. 😅

**Comment by robdodson** [comment]
@kbrsh is it looking for `firstChild` or `firstElementChild`? The second one would skip text nodes I think.

**Comment by kbrsh** [comment]
@robdodson Haha neither. Moon has a compiler (lex, parse, then generate code) that creates a render function for virtual DOM. That is what allows it to detect static nodes and skip them over when diffing.

**Pull request merged**
