### PR TITLE
Add DIO

### PR DESCRIPTION
**Pull request by thysultan**
Mostly ported from the preact example. Let me know if i missed something.

Thanks.

### CODE REVIEW

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
Thanks for adding this! A couple questions:

- Do you have any open issues to fix the failing tests?
- How stable would you say DIO is? In the past I've had to remove projects that were added because they were still fairly young and shipping a lot of breaking changes. When the library ships a breaking change the burden of maintenance falls on me and sometimes it can be a lot of work to get the site building again.

**Comment by thysultan** [comment]
There are currently no open issues related to the failing tests, is this required? 

>How stable would you say DIO is?

It is fairly stable.

**Comment by robdodson** [comment]
> There are currently no open issues related to the failing tests, is this required?

It's nice to do if you intend to fix them or want to have a place for folks to discuss the issue.

Would you mind rebasing the PR against master? Then we can look at getting it merged in.

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
Should be merged into master now

**Comment by thysultan** [comment]
Thanks.

**Pull request closed without merging**
